/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "git-2019-11-22-27c6c92"
#endif /* AVUTIL_FFVERSION_H */
